apiVersion: v1
kind: ConfigMap
metadata:
  name: vortex-client-config
  namespace: vortex-client
data:
  VITE_API_URL: "https://api.vortex.example.com/api"
  VITE_CLOUDINARY_CLOUD_NAME: "your-cloud-name"
